apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app: sample-python-deployment
  ports:
    - port: 80
      targetPort: 8000
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 30007
